.test_build_template: &test_build_latest
  script:
    - export REL_OS_NAME=$(lsb_release -is)
    - export REL_OS_VERS=$(lsb_release -rs | sed -r "s/^([0-9]+).*/\1/")
    - export REL_PROJECT_NAME=$CI_PROJECT_NAME
    - export REL_TAG=$CI_BUILD_REF_NAME
    - export KARABO_TAG="latest_build"
    - export GIT_TOKEN=$XFEL_TOKEN
    - export CI_BUILD="LATEST"
    - export KARABO_BROKER_TOPIC="gitlab_ci_$CI_JOB_ID"
    - curl http://exflserv05.desy.de/karabo/karaboFramework/tags/$KARABO_TAG/karabo-$KARABO_TAG-Release-$REL_OS_NAME-$REL_OS_VERS-x86_64.sh > karabo.sh
    - bash karabo.sh --prefix=/root
    - source /root/karabo/activate
    - git config --global user.email "xfel.redmine@xfel.eu"
    - git config --global user.name "xfel.redmine"
    - cd $CI_PROJECT_DIR
    # install depends
    - >
        if test -f "DEPENDS"; then
           IFS=","
           while read line; do
               [[ $line =~ ^#.* ]] && continue
               norm=${line/,/ }
               norm=`echo $norm | sed -e "s/[[:space:]]\+/ /g"`
               device=$(echo $norm | cut -f1 -d' ')
               tag=$(echo $norm | cut -f2 -d' ')
               echo $device
               echo $tag
               karabo -g https://$XFEL_TOKEN@git.xfel.eu/gitlab install $device $tag
           done < DEPENDS        
        fi;


    - pip install -e . 
    # run a device server to test for syntax errors
    - karabo-middlelayerserver serverId=test > test.log &
    - karabo-pythonserver serverId=test2 >> test.log &
    - sleep 15
    - if [[ $(grep -e SyntaxError -e ImportError test.log) ]]; then exit 1; else exit 0; fi
    # uncomment this line to enable actual unit tests!
    - nosetests .


test:centos7-latest:
  image: europeanxfel/karabo-ci:centos-7gcc7
  before_script:
    - source /opt/rh/devtoolset-7/enable
  <<: *test_build_latest

